version:0.0
0s:linux
files:
  -source: /index.html
   destination:/var/www/html/
hooks:
  BrforeInstall:
      -location: /script/install_dependancies
       timeout: 300
       runas:roots
      -location: /scripts/start_server
       timeout: 300
       runas:root